version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3306"
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_HOSTNAME: db
      DB_NAME: mydb
      DB_PORT: 3306
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    restart: always
  web:
    build:
      context: ./ngnix
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "4000:80"
